name: Playground repository snapshot & deployment

permissions: {}

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest

    permissions:
      id-token: 'write' # for OIDC needed for Google Cloud authentication
      contents: 'write' # for commiting the snapshot/timestamp changes

    outputs:
      generated: ${{ steps.snapshot.outputs.generated }}

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d
        with:
          token_format: access_token
          workload_identity_provider: projects/843741030650/locations/global/workloadIdentityPools/git-repo-demo/providers/git-repo-demo
          service_account: git-repo-demo@python-tuf-kms.iam.gserviceaccount.com

      - id: snapshot
        uses: jku/repository-playground/playground/actions/snapshot@git-repo-snapshot

  deploy:
    permissions:
      pages: write
      id-token: write # for authenticating to GH Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: snapshot
    if: needs.snapshot.outputs.generated
    steps:
      - name: Deploy Playground repository to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@0243b6c10d06cb8e95ed8ee471231877621202c0
