name: Version bumps

on:
  schedule:
    - cron:  '17 1,7,13,19 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  online-version-bump:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write' # for OIDC auth for GCP authentication
      contents: 'write' # for committing to main
    outputs:
      generated: ${{ steps.online-bump.outputs.generated }}
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d
        with:
          token_format: access_token
          workload_identity_provider: YOUR_IDENTITY_PROVIDER_HERE
          service_account: YOUR_SERVICE_ACCOUNT_HERE
      - id: online-bump
        uses: jku/repository-playground/playground/actions/online-version-bump@main

  offline-version-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write' # for committing to signing event branch
      actions: 'write' # for dispatching signing event workflow
    steps:
      - name: Create signing events for offline version bumps
        uses: jku/repository-playground/playground/actions/offline-version-bump@main

  deploy:
    permissions:
      pages: write
      id-token: write # for authenticating to GH Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: online-version-bump
    if: needs.online-version-bump.outputs.generated == 'true'
    steps:
      - name: Deploy Playground repository to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@0243b6c10d06cb8e95ed8ee471231877621202c0
